export enum DocTypeEnum {
    AddressProof=31,
    Photo=30,
    IdProof=32,
    PI = '05',
    Proposal = '06',
    CoverLetter = '07',
    SignOffAndDataHandover=45,
    UC=40,
    WorkOrder=34,
    StRS= '08',
    StRS_Approval='09',
    MOU_Signed='04',
    MOU_UnSigned='03',
}